version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: "13.4.1"
#    resource_class: macos.x86.medium.gen2
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2.1
  build-test:
    jobs:
      - build-and-test
